; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = NMAxe
packages_dir = .pio/packages

[env:NMAxe]
platform = espressif32@6.6.0
board = AxeSeries
framework = arduino
upload_protocol = custom
build_src_filter =
    -<*>
    +<../src/main.cpp>
    +<../src/app/>
    +<../src/thread/>
    +<../src/mining/>
    +<../src/board/>
    +<../src/utils/>
    +<../src/nvs/>
    +<../src/drivers/iic/>
    +<../src/drivers/asic/>
    +<../src/drivers/temp/>
    +<../src/drivers/touch/>
    +<../src/drivers/power/>
    +<../src/drivers/extio/>
    +<../src/drivers/fan/>
    +<../src/drivers/display/>
    +<../src/market/>
    +<../src/stratum/>
    +<../src/web/http_server.cpp>
    +<../src/ui/>
    +<../src/ui/assets/>
    +<../src/ui/assets/fonts/>
    +<../src/patches/etharp.c>
board_build.filesystem = spiffs
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = partitions/partitions.csv
board_build.arduino.memory_type = qio_opi
board_build.flash_size = 16MB
build_flags =
    -std=c++17
    -iquote "./src"
    -I "./src"
    -D BOARD_HAS_PSRAM
    -D CONFIG_LWIP_ARP_TABLE_SIZE=32
    -D LWIP_ARP_QUEUE_LEN=1
    -D LV_LVGL_H_INCLUDE_SIMPLE=1
    -D LV_CONF_INCLUDE_SIMPLE=1
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_DEBUG_LEVEL=0
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=0
    -D LVGL_ENABLE
    -Wl,--allow-multiple-definition
lib_deps =
    bblanchon/ArduinoJson@^6.21.5
    mathertel/OneButton@^2.5.0
    arduino-libraries/NTPClient@^3.2.1
    https://github.com/ESP32Async/AsyncTCP.git#v3.4.10
    https://github.com/mathieucarbou/ESPAsyncWebServer.git#v3.6.0
    lvgl/lvgl@^8.4.0
    adafruit/Adafruit NeoPixel@^1.10.0
extra_scripts = pre:build_web.py
upload_command = esptool.py --chip esp32s3 --port $UPLOAD_PORT --baud $UPLOAD_SPEED --before default_reset --after hard_reset write_flash -z --flash_mode keep --flash_freq 80m --flash_size 16MB 0x0000 partitions\bootloader.bin 0xf90000 partitions\ota_data_initial.bin 0x8000 .pio\build\NMAxe\partitions.bin 0x10000 .pio\build\NMAxe\firmware.bin 0x410000 .pio\build\NMAxe\spiffs.bin
platform_packages =
    framework-arduinoespressif32@~3.20014.0
    platformio/tool-esptoolpy@^1.40501.0
