#pragma once
#include "lvgl.h"

// Custom fonts ported from the legacy UI (compiled from the .c files alongside).
LV_FONT_DECLARE(ds_digib_font_16)
LV_FONT_DECLARE(ds_digib_font_18)
LV_FONT_DECLARE(ds_digib_font_20)
LV_FONT_DECLARE(ds_digib_font_24)
LV_FONT_DECLARE(ds_digib_font_28)
LV_FONT_DECLARE(ds_digib_font_32)
LV_FONT_DECLARE(ds_digib_font_36)
LV_FONT_DECLARE(ds_digib_font_38)
LV_FONT_DECLARE(ds_digib_font_52)
LV_FONT_DECLARE(ds_digib_font_56)
LV_FONT_DECLARE(ds_digib_font_120)
LV_FONT_DECLARE(Inconsolata_14)
LV_FONT_DECLARE(Inconsolata_16)
LV_FONT_DECLARE(Inconsolata_18)
LV_FONT_DECLARE(Inconsolata_22)
LV_FONT_DECLARE(Inconsolata_26)
LV_FONT_DECLARE(symbol_14)
LV_FONT_DECLARE(symbol_16)
LV_FONT_DECLARE(symbol_18)
LV_FONT_DECLARE(symbol_20)
LV_FONT_DECLARE(symbol_22)
LV_FONT_DECLARE(symbol_24)
LV_FONT_DECLARE(symbol_26)
LV_FONT_DECLARE(symbol_28)
LV_FONT_DECLARE(symbol_30)
