#ifndef RECOVERY_PAGE
#define RECOVERY_PAGE

// IMPORTANT: The upload uses multipart/form-data (FormData) so that
// AsyncWebServer's file-upload callback (file_upload_handler) is triggered.
// Sending raw binary with Content-Type:application/octet-stream bypasses the
// upload callback entirely — the body data is silently discarded and OTA never
// starts. FormData is the same mechanism the main Angular app uses.

const char recovery_page[] =
"<!DOCTYPE html>"
"<html lang='en'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>AxeOS Recovery</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{"
"  background:#0a0a0a;"
"  color:#00e676;"
"  font-family:'Courier New',monospace;"
"  min-height:100vh;"
"  display:flex;"
"  align-items:center;"
"  justify-content:center;"
"}"
".card{"
"  background:#111;"
"  border:1px solid #00e67633;"
"  border-radius:12px;"
"  padding:2.5rem 3rem;"
"  width:100%;"
"  max-width:520px;"
"  box-shadow:0 0 40px #00e67611;"
"}"
".logo-block{text-align:center;margin-bottom:1.8rem}"
".logo-title{"
"  font-size:2.6rem;"
"  font-weight:bold;"
"  color:#00e676;"
"  letter-spacing:0.18em;"
"  text-shadow:0 0 24px #00e67666,0 0 6px #00e67633;"
"  line-height:1;"
"}"
".logo-sub{"
"  font-size:0.7rem;"
"  color:#607d8b;"
"  letter-spacing:0.45em;"
"  text-transform:uppercase;"
"  margin-top:0.5rem;"
"  text-shadow:0 0 8px #00e67633;"
"}"
"h2{"
"  text-align:center;"
"  font-size:1rem;"
"  font-weight:normal;"
"  color:#b0bec5;"
"  margin-bottom:0.5rem;"
"  letter-spacing:0.08em;"
"  text-transform:uppercase;"
"}"
".warning{"
"  text-align:center;"
"  font-size:0.8rem;"
"  color:#ff7043;"
"  margin-bottom:1.8rem;"
"  line-height:1.6;"
"  padding:0.6rem 0.8rem;"
"  border:1px solid #ff704322;"
"  border-radius:6px;"
"  background:#1a0d0a;"
"}"
".file-row{"
"  display:flex;"
"  gap:0.6rem;"
"  align-items:center;"
"  margin-bottom:1rem;"
"}"
".file-label{"
"  display:inline-flex;"
"  align-items:center;"
"  gap:0.4rem;"
"  padding:0.5rem 1rem;"
"  background:#1a1a1a;"
"  border:1px solid #00e67655;"
"  border-radius:8px;"
"  cursor:pointer;"
"  font-family:inherit;"
"  font-size:0.82rem;"
"  color:#00e676;"
"  transition:border-color .2s,background .2s;"
"  white-space:nowrap;"
"  user-select:none;"
"}"
".file-label:hover{background:#1e2e1e;border-color:#00e676}"
".file-label.disabled{opacity:0.35;cursor:not-allowed;pointer-events:none}"
"#wwwfile{display:none}"
"#filename{"
"  flex:1;"
"  font-size:0.78rem;"
"  color:#78909c;"
"  overflow:hidden;"
"  text-overflow:ellipsis;"
"  white-space:nowrap;"
"}"
".btn{"
"  width:100%;"
"  padding:0.65rem;"
"  border:none;"
"  border-radius:8px;"
"  font-family:inherit;"
"  font-size:0.88rem;"
"  cursor:pointer;"
"  transition:opacity .2s,transform .05s;"
"  font-weight:bold;"
"  letter-spacing:0.05em;"
"}"
".btn:active{transform:scale(0.98)}"
".btn:disabled{opacity:0.35;cursor:not-allowed;transform:none}"
".btn-primary{background:#00e676;color:#000;margin-bottom:0.7rem}"
".btn-primary:hover:not(:disabled){opacity:0.85}"
".btn-restart{background:#1a1a1a;color:#90a4ae;border:1px solid #2a2a2a}"
".btn-restart:hover:not(:disabled){background:#1e2424;border-color:#00e67644;color:#b0bec5}"
".btn-dl{background:#0d1b2a;color:#4fc3f7;border:1px solid #1e3a5f;font-size:1rem;padding:0.65rem 1rem;margin-top:0}"
".btn-dl:hover:not(:disabled){background:#112233;border-color:#4fc3f7;color:#81d4fa}"
".progress-wrap{margin:1rem 0;display:none}"
".progress-bar{"
"  height:6px;"
"  background:#1a1a1a;"
"  border-radius:3px;"
"  overflow:hidden;"
"  margin-bottom:0.4rem;"
"}"
".progress-fill{"
"  height:100%;"
"  width:0%;"
"  background:linear-gradient(90deg,#00bfa5,#00e676);"
"  border-radius:3px;"
"  transition:width .25s ease;"
"}"
".progress-text{text-align:center;font-size:0.75rem;color:#78909c}"
"#status-msg{"
"  text-align:center;"
"  font-size:0.8rem;"
"  min-height:1.3em;"
"  margin-bottom:0.8rem;"
"  color:#78909c;"
"  transition:color .2s;"
"}"
"#status-msg.ok{color:#00e676}"
"#status-msg.err{color:#ff5722}"
".divider{border:none;border-top:1px solid #1c1c1c;margin:1.5rem 0 1rem}"
".help{text-align:center;font-size:0.73rem;color:#546e7a;line-height:1.7}"
".help a{color:#00b0ff;text-decoration:none}"
".help a:hover{text-decoration:underline}"
"</style>"
"</head>"
"<body>"
"<div class='card'>"

"<div class='logo-block'>"
"<div class='logo-title'>AxeOS</div>"
"<div class='logo-sub'>&#x25cf;&nbsp;&nbsp;Recovery Mode&nbsp;&nbsp;&#x25cf;</div>"
"</div>"

"<h2>SPIFFS Recovery Mode</h2>"

"<div class='warning'>"
"Web filesystem is missing or corrupt.<br>"
"Please upload <strong>spiffs.bin</strong> to restore AxeOS."
"</div>"

"<div class='file-row'>"
"<label class='file-label' for='wwwfile'>&#128193; Choose File</label>"
"<span id='filename'>No file selected</span>"
"</div>"
"<input type='file' id='wwwfile' accept='.bin'>"

"<div class='progress-wrap' id='progress-wrap'>"
"<div class='progress-bar'><div class='progress-fill' id='prog-fill'></div></div>"
"<div class='progress-text' id='prog-text'>0%</div>"
"</div>"

"<p id='status-msg'></p>"

"<button class='btn btn-primary' id='upload-btn' onclick='handleUpload()'>&#11014; Upload spiffs.bin</button>"
"<button class='btn btn-restart' id='restart-btn' onclick='handleRestart()'>&#8635; Restart Device</button>"

"<hr class='divider'>"
"<div class='help'>"
"<button class='btn btn-dl' id='dl-btn' onclick='downloadLatest()'>&#11015; Download latest release</button>"
"<div id='dl-status' style='margin-top:8px;font-size:0.92rem;color:#b0bec5'></div>"
"</div>"
"</div>"

"<script>"
"document.getElementById('wwwfile').addEventListener('change',function(){"
"  var file=this.files[0];"
"  if(!file)return;"
"  if(file.name!=='spiffs.bin'){"
"    this.value='';"
"    document.getElementById('filename').textContent='No file selected';"
"    setStatus('Wrong file \u2014 only spiffs.bin is accepted.','err');"
"    return;"
"  }"
"  document.getElementById('filename').textContent=file.name;"
"  document.getElementById('wwwfile').disabled=true;"
"  document.querySelector('.file-label').classList.add('disabled');"
"  setStatus('','');"
"});"

"function setStatus(msg,cls){"
"  var el=document.getElementById('status-msg');"
"  el.textContent=msg;el.className=cls||'';"
"}"

// Upload uses FormData (multipart/form-data) so AsyncWebServer routes the data
// through file_upload_handler. Raw binary (application/octet-stream) bypasses
// the upload callback — the OTA would never start.
"function handleUpload(){"
"  var file=document.getElementById('wwwfile').files[0];"
"  if(!file){setStatus('Please select spiffs.bin first.','err');return;}"
"  if(file.name!=='spiffs.bin'){setStatus('Wrong file \u2014 select spiffs.bin','err');return;}"
"  document.getElementById('upload-btn').disabled=true;"
"  document.getElementById('restart-btn').disabled=true;"
"  document.getElementById('progress-wrap').style.display='block';"
"  setStatus('Uploading, please wait\u2026','');"
"  var fd=new FormData();"
"  fd.append('update',file,file.name);"
"  var xhr=new XMLHttpRequest();"
"  xhr.open('POST','/api/system/OTAWWW',true);"
"  xhr.upload.onprogress=function(e){"
"    if(e.lengthComputable){"
"      var p=Math.round(e.loaded/e.total*100);"
"      document.getElementById('prog-fill').style.width=p+'%';"
"      document.getElementById('prog-text').textContent=p+'%';"
"    }"
"  };"
"  xhr.onload=function(){"
"    document.getElementById('upload-btn').disabled=false;"
"    document.getElementById('restart-btn').disabled=false;"
"    document.getElementById('wwwfile').disabled=false;"
"    document.querySelector('.file-label').classList.remove('disabled');"
"    if(xhr.status===200){"
"      document.getElementById('prog-fill').style.width='100%';"
"      document.getElementById('prog-text').textContent='100%';"
"      setStatus('Upload successful! Device is rebooting\u2026','ok');"
"    }else{"
"      setStatus('Upload failed (HTTP '+xhr.status+'): '+xhr.responseText,'err');"
"    }"
"  };"
"  xhr.onerror=function(){"
"    document.getElementById('upload-btn').disabled=false;"
"    document.getElementById('restart-btn').disabled=false;"
"    document.getElementById('wwwfile').disabled=false;"
"    document.querySelector('.file-label').classList.remove('disabled');"
"    setStatus('Network error \u2014 check device connection.','err');"
"  };"
"  xhr.send(fd);"
"}"

"function downloadLatest(){"
"  var btn=document.getElementById('dl-btn');"
"  var info=document.getElementById('dl-status');"
"  btn.disabled=true;btn.textContent='Fetching release info\u2026';"
"  info.textContent='';"
"  fetch('https://api.github.com/repos/NMminer1024/ESP-Miner-NMAxe/releases')"
"    .then(function(r){return r.json();})"
"    .then(function(releases){"
"      var stable=releases.filter(function(r){return !r.prerelease;});"
"      if(!stable.length){throw new Error('No stable release found.');}"
"      var rel=stable[0];"
"      var zipName=rel.tag_name+'.zip';"
"      var asset=(rel.assets||[]).find(function(a){return a.name===zipName;});"
"      if(!asset){throw new Error('ZIP asset '+zipName+' not found in release.');}"
"      info.textContent='Downloading '+asset.name+' (v'+rel.tag_name+')';"
"      var a=document.createElement('a');"
"      a.href=asset.browser_download_url;"
"      a.download=asset.name;"
"      a.target='_blank';"
"      document.body.appendChild(a);a.click();document.body.removeChild(a);"
"      btn.disabled=false;btn.textContent='\u2b07 Download latest release';"
"    })"
"    .catch(function(e){"
"      info.style.color='#e74c3c';"
"      info.textContent='Error: '+e.message;"
"      btn.disabled=false;btn.textContent='\u2b07 Download latest release';"
"    });"
"}"
""
"function handleRestart(){"
"  setStatus('Sending restart command\u2026','');"
"  var xhr=new XMLHttpRequest();"
"  xhr.open('POST','/api/system/restart',true);"
"  xhr.onload=function(){setStatus(xhr.responseText||'Restarting\u2026','ok');};"
"  xhr.onerror=function(){setStatus('Failed to reach device.','err');};"
"  xhr.send(null);"
"}"
"</script>"
"</body>"
"</html>";

#endif
